## 逻辑运算

In [1]:
import numpy as np
# 生成10名同学，5门功课的数据
score = np.random.randint(40, 100, (10, 5)) # 生成一个10x5的二维数组里面额值的区间在40-100之间
score

array([[69, 60, 83, 52, 56],
       [66, 74, 70, 75, 76],
       [61, 77, 80, 68, 74],
       [56, 89, 57, 71, 49],
       [69, 49, 87, 58, 67],
       [84, 92, 51, 59, 98],
       [92, 47, 56, 44, 99],
       [86, 91, 83, 84, 68],
       [46, 45, 49, 50, 57],
       [81, 40, 95, 93, 75]])

In [5]:
# 取出最后4名同学的成绩，用于逻辑判断
test_score = score[6:, 0:5]
test_score

array([[92, 47, 56, 44, 99],
       [86, 91, 83, 84, 68],
       [46, 45, 49, 50, 57],
       [81, 40, 95, 93, 75]])

In [6]:
# 逻辑判断, 如果成绩大于60就标记为True 否则为False
test_score > 60

array([[ True, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [ True, False,  True,  True,  True]])

In [7]:
test_score[test_score > 60] = 1
test_score

array([[ 1, 47, 56, 44,  1],
       [ 1,  1,  1,  1,  1],
       [46, 45, 49, 50, 57],
       [ 1, 40,  1,  1,  1]])

通用判断函数

In [9]:
# 判断前两名同学的成绩[0:2, :]是否全及格
np.all(score[0:2, :] > 60)

False

np.any()

In [10]:
# 判断前两名同学的成绩[0:2, :]是否有大于90分的
np.any(score[0:2, :] > 80)

True

np.where(三元运算符)

In [11]:
# 判断前四名学生,前四门课程中，成绩中大于60的置为1，否则为0
temp = score[:4, :4]
np.where(temp > 60, 1, 0)

array([[1, 0, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [0, 1, 0, 1]])